FROM tensorflow/tensorflow:2.9.1-gpu-jupyter
ENV HOME=/project
WORKDIR /project
COPY app/requirements.txt .
RUN pip install \
      --no-cache-dir \
      -r requirements.txt \
    && mkdir -p runs \
    && mkdir -p models
COPY app/ .
ENTRYPOINT [ "python3" ]
