name: ec2-runner
on:
  push:
    branches:
      - main
      - "releases/**"

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-024643308e9ca105c
          # cheap
          ec2-instance-type: g4dn.12xlarge
          # g4dn.12xlarge  4x 16GB T4 (CC 7.5)   - $3.91
          # g4dn.metal     8x 16GB T4 (CC 7.5)   - $7.82
          # p3.8xlarge     4x 16GB V100 (CC 7.0) - $12.24

          subnet-id: subnet-0d00e9c357708b486 # public 1b
          security-group-id: sg-0cb78c31930887d16 # public 1b
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]
  generate-net:
    name: Generate Morse Neural Net
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    timeout-minutes: 240 # 4hrs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./app
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-timeout

      - name: NVIDIA-SMI
        run: nvidia-smi

      - name: Versions
        working-directory: ./app
        run: |
          python3.9 --version
          pip --version
          pip list

      - name: Generate Net
        working-directory: ./app
        run: |
          python3.9 main.py --total 3000
        env:
          TF_ENABLE_ONEDNN_OPTS: 0

      - name: Archive Models
        uses: actions/upload-artifact@v3
        with:
          name: models
          if-no-files-found: error
          retention-days: 7
          path: |
            app/models/*

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - generate-net # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
