name: local-runner
on:
  push:
    branches:
      - develop

jobs:
  generate-net:
    name: Generate Morse Neural Net
    runs-on: self-hosted-free
    timeout-minutes: 1440 # 24hrs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NVIDIA-SMI
        run: nvidia-smi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: false
          load: true
          file: Dockerfile.dev
          tags: stefancrain/nn-morse:builder
      - name: Generate Net
        run: |
          docker volume create nn-morse-${{ github.sha }}
          docker run --name=nn-morse-${{ github.sha }} -v nn-morse-${{ github.sha }}:/project --ipc=host --gpus=all stefancrain/nn-morse:builder main.py --max 20
      - name: Copy out file from Container
        if: always()
        timeout-minutes: 5
        run: |
          docker pull ubuntu:22.04
          docker run --rm -v nn-morse-${{ github.sha }}:/project ubuntu:22.04 tar -cO /project/models | gzip -c > models.tgz
          docker run --rm -v nn-morse-${{ github.sha }}:/project ubuntu:22.04 tar -cO /project/runs | gzip -c > runs.tgz
      - name: Archive Models
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: models
          if-no-files-found: error
          retention-days: 7
          path: |
            models.tgz
            runs.tgz
      - name: Remove container
        if: always()
        run: |
          docker rm -f nn-morse-${{ github.sha }}
          docker volume rm -f nn-morse-${{ github.sha }}
