name: local-runner
on:
  push:
    branches:
      - develop

jobs:
  generate-net:
    name: Generate Morse Neural Net
    runs-on: self-hosted-free
    timeout-minutes: 1440 # 24hrs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NVIDIA-SMI
        run: nvidia-smi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          file: Dockerfile.dev
          tags: stefancrain/nn-morse:builder
      - name: Generate Net
        run: |
          docker run --rm stefancrain/nn-morse:builder "main.py --max 100"
